### ISSUE TITLE
Discrete Cosine Transform

### ISSUE THREAD

**Issue by astewart-xmos** [xmos/lib_xcore_math#75]
`lib_dsp` has a [discrete cosine transform](https://github.com/xmos/lib_dsp/blob/develop/lib_dsp/api/dsp_dct.h) implementation.

It would probably be good to have this in lib_xs3_math.  I don't know the details yet, so I'm not sure whether this is something that can be accelerated by the VPU.

**Comment by danielpieczko** [comment]
To add support to this feature request, the VAD uses a [24-point DCT](https://github.com/xmos/lib_vad/blob/ce6db09fa797a34b0f2de15d46ca8886f90d24f7/lib_vad/src/vad.xc#L143) which it gets from lib_dsp, so an implementation in lib_xs3_math could benefit the VAD implementation for sw_avona.

**Comment by ed-xmos** [comment]
Note as a workaround to the missing DCT function we have copied the DCT implementation from lib_dsp to support the avona VAD in the short term. Not ideal but we are looking at superseding vad anyhow which will likely use log mels rather than cepstrum.
However any MFCC implementation (very common in ASR) will require a DCT implementation. 
https://en.wikipedia.org/wiki/Mel-frequency_cepstrum

**Comment by astewart-xmos** [comment]
Closing this issue as it was implemented in PR #98.
